export const colleges = [
  {
    featured: false,
    college_logo:
      "https://logowik.com/content/uploads/images/iit-delhi-indian-institute-of-technology-delhi5001.jpg",
    college_name: "Indian Institute of Technology Delhi",
    college_city: "New Delhi",
    college_state: "Delhi NCR",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: true,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: true,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: true,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: true,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: true,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: true,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: true,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: true,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: true,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: true,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: true,
    college_logo: "https://i.imgur.com/bIu4tDU.png",
    college_name: "BT Macras Indian Institute of Technology",
    college_city: "TTM",
    college_state: "Chennai",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 0.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
];
