export const colleges = [
  {
    featured: false,
    college_logo:
      "https://logowik.com/content/uploads/images/iit-delhi-indian-institute-of-technology-delhi5001.jpg",
    college_name: "Indian Institute of Technology Delhi",
    college_city: "New Delhi",
    college_state: "Delhi NCR",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,07,550",
    placement: {
      average_package: "21.46 LPA",
      highest_package: "42.00 LPA",
    },
    user_reviews: {
      rating: 8.6,
      no_of_users: 3131,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo:
      "https://logowik.com/content/uploads/images/iit-bombay-indian-institute-of-technology-bombay5002.jpg",
    college_name: "Indian Institute of Technology Bombay",
    college_city: "Mumbai",
    college_state: "Maharashtra",
    institutions_approved: ["AICTE", "COA"],
    last_year_jee_advanced_btech_cse_cutoff: 145,
    course_fees: "2,50,000",
    placement: {
      average_package: "25.00 LPA",
      highest_package: "48.00 LPA",
    },
    user_reviews: {
      rating: 8.9,
      no_of_users: 367,
      best_in: "Infrastructure",
    },
    ranking: 75,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Birla Institute of Technology and Science, Pilani",
    college_city: "Pilani",
    college_state: "Rajasthan",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 140,
    course_fees: "3,00,000",
    placement: {
      average_package: "16.00 LPA",
      highest_package: "34.00 LPA",
    },
    user_reviews: {
      rating: 8.0,
      no_of_users: 450,
      best_in: "Social Life",
    },
    ranking: 60,
  },
  {
    featured: false,
    college_logo:
      "https://logowik.com/content/uploads/images/iit-kanpur-indian-institute-of-technology-kanpur5003.jpg",
    college_name: "Indian Institute of Technology Kanpur",
    college_city: "Kanpur",
    college_state: "Uttar Pradesh",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 160,
    course_fees: "1,80,000",
    placement: {
      average_package: "20.00 LPA",
      highest_package: "40.00 LPA",
    },
    user_reviews: {
      rating: 8.5,
      no_of_users: 289,
      best_in: "Social Life",
    },
    ranking: 105,
  },
  {
    featured: false,
    college_logo:
      "https://logowik.com/content/uploads/images/iit-madras-indian-institute-of-technology-madras5004.jpg",
    college_name: "Indian Institute of Technology Madras",
    college_city: "Chennai",
    college_state: "Tamil Nadu",
    institutions_approved: ["AICTE", "COA"],
    last_year_jee_advanced_btech_cse_cutoff: 150,
    course_fees: "2,20,000",
    placement: {
      average_package: "23.00 LPA",
      highest_package: "45.00 LPA",
    },
    user_reviews: {
      rating: 9.0,
      no_of_users: 402,
      best_in: "Infrastructure",
    },
    ranking: 85,
  },
  {
    featured: false,
    college_logo:
      "https://logowik.com/content/uploads/images/iit-roorkee-indian-institute-of-technology-roorkee5005.jpg",
    college_name: "Indian Institute of Technology Roorkee",
    college_city: "Roorkee",
    college_state: "Uttarakhand",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 165,
    course_fees: "2,30,000",
    placement: {
      average_package: "19.00 LPA",
      highest_package: "38.00 LPA",
    },
    user_reviews: {
      rating: 8.7,
      no_of_users: 341,
      best_in: "Social Life",
    },
    ranking: 110,
  },
  {
    featured: false,
    college_logo:
      "https://logowik.com/content/uploads/images/iit-guwahati-indian-institute-of-technology-guwahati5006.jpg",
    college_name: "Indian Institute of Technology Guwahati",
    college_city: "Guwahati",
    college_state: "Assam",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 140,
    course_fees: "2,10,000",
    placement: {
      average_package: "18.50 LPA",
      highest_package: "37.00 LPA",
    },
    user_reviews: {
      rating: 8.4,
      no_of_users: 275,
      best_in: "Infrastructure",
    },
    ranking: 120,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Vellore Institute of Technology",
    college_city: "Vellore",
    college_state: "Tamil Nadu",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 120,
    course_fees: "3,50,000",
    placement: {
      average_package: "12.00 LPA",
      highest_package: "30.00 LPA",
    },
    user_reviews: {
      rating: 7.8,
      no_of_users: 490,
      best_in: "Infrastructure",
    },
    ranking: 80,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "SRM Institute of Science and Technology",
    college_city: "Chennai",
    college_state: "Tamil Nadu",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 130,
    course_fees: "3,20,000",
    placement: {
      average_package: "14.50 LPA",
      highest_package: "32.00 LPA",
    },
    user_reviews: {
      rating: 7.9,
      no_of_users: 480,
      best_in: "Social Life",
    },
    ranking: 85,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Manipal Institute of Technology",
    college_city: "Manipal",
    college_state: "Karnataka",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 125,
    course_fees: "3,40,000",
    placement: {
      average_package: "13.50 LPA",
      highest_package: "31.00 LPA",
    },
    user_reviews: {
      rating: 7.7,
      no_of_users: 470,
      best_in: "Social Life",
    },
    ranking: 90,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "BITS, Pilani - Hyderabad Campus",
    college_city: "Hyderabad",
    college_state: "Telangana",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 135,
    course_fees: "3,60,000",
    placement: {
      average_package: "15.00 LPA",
      highest_package: "33.00 LPA",
    },
    user_reviews: {
      rating: 8.1,
      no_of_users: 455,
      best_in: "Infrastructure",
    },
    ranking: 95,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Amity University",
    college_city: "Noida",
    college_state: "Uttar Pradesh",
    institutions_approved: ["UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 140,
    course_fees: "3,80,000",
    placement: {
      average_package: "11.50 LPA",
      highest_package: "29.00 LPA",
    },
    user_reviews: {
      rating: 7.5,
      no_of_users: 500,
      best_in: "Social Life",
    },
    ranking: 100,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Christ University",
    college_city: "Bengaluru",
    college_state: "Karnataka",
    institutions_approved: ["UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 150,
    course_fees: "3,50,000",
    placement: {
      average_package: "12.50 LPA",
      highest_package: "30.00 LPA",
    },
    user_reviews: {
      rating: 8.3,
      no_of_users: 490,
      best_in: "Infrastructure",
    },
    ranking: 105,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Lovely Professional University",
    college_city: "Jalandhar",
    college_state: "Punjab",
    institutions_approved: ["UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 160,
    course_fees: "3,00,000",
    placement: {
      average_package: "10.00 LPA",
      highest_package: "28.00 LPA",
    },
    user_reviews: {
      rating: 7.2,
      no_of_users: 480,
      best_in: "Social Life",
    },
    ranking: 110,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Symbiosis Institute of Technology",
    college_city: "Pune",
    college_state: "Maharashtra",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 145,
    course_fees: "3,30,000",
    placement: {
      average_package: "13.00 LPA",
      highest_package: "31.00 LPA",
    },
    user_reviews: {
      rating: 7.6,
      no_of_users: 470,
      best_in: "Infrastructure",
    },
    ranking: 115,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Thapar Institute of Engineering and Technology",
    college_city: "Patiala",
    college_state: "Punjab",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "3,40,000",
    placement: {
      average_package: "14.00 LPA",
      highest_package: "32.00 LPA",
    },
    user_reviews: {
      rating: 7.9,
      no_of_users: 490,
      best_in: "Infrastructure",
    },
    ranking: 120,
  },
  {
    featured: false,
    college_logo:
      "https://logowik.com/content/uploads/images/iit-bhubaneswar-indian-institute-of-technology-bhubaneswar5007.jpg",
    college_name: "Indian Institute of Technology Bhubaneswar",
    college_city: "Bhubaneswar",
    college_state: "Odisha",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 170,
    course_fees: "2,40,000",
    placement: {
      average_package: "22.00 LPA",
      highest_package: "44.00 LPA",
    },
    user_reviews: {
      rating: 8.8,
      no_of_users: 312,
      best_in: "Infrastructure",
    },
    ranking: 100,
  },
  {
    featured: false,
    college_logo:
      "https://logowik.com/content/uploads/images/iit-hyderabad-indian-institute-of-technology-hyderabad5008.jpg",
    college_name: "Indian Institute of Technology Hyderabad",
    college_city: "Hyderabad",
    college_state: "Telangana",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 135,
    course_fees: "2,30,000",
    placement: {
      average_package: "18.00 LPA",
      highest_package: "36.00 LPA",
    },
    user_reviews: {
      rating: 8.3,
      no_of_users: 258,
      best_in: "Social Life",
    },
    ranking: 130,
  },
  {
    featured: false,
    college_logo:
      "https://logowik.com/content/uploads/images/iit-kharagpur-indian-institute-of-technology-kharagpur5010.jpg",
    college_name: "Indian Institute of Technology Kharagpur",
    college_city: "Kharagpur",
    college_state: "West Bengal",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 130,
    course_fees: "2,60,000",
    placement: {
      average_package: "24.00 LPA",
      highest_package: "46.00 LPA",
    },
    user_reviews: {
      rating: 8.9,
      no_of_users: 390,
      best_in: "Infrastructure",
    },
    ranking: 80,
  },
  {
    featured: false,
    college_logo:
      "https://logowik.com/content/uploads/images/iit-ropar-indian-institute-of-technology-ropar5011.jpg",
    college_name: "Indian Institute of Technology Ropar",
    college_city: "Ropar",
    college_state: "Punjab",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 180,
    course_fees: "2,50,000",
    placement: {
      average_package: "20.50 LPA",
      highest_package: "41.00 LPA",
    },
    user_reviews: {
      rating: 8.7,
      no_of_users: 335,
      best_in: "Social Life",
    },
    ranking: 115,
  },
  {
    featured: false,
    college_logo:
      "https://logowik.com/content/uploads/images/iit-patna-indian-institute-of-technology-patna5012.jpg",
    college_name: "Indian Institute of Technology Patna",
    college_city: "Patna",
    college_state: "Bihar",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 140,
    course_fees: "2,30,000",
    placement: {
      average_package: "19.50 LPA",
      highest_package: "39.00 LPA",
    },
    user_reviews: {
      rating: 8.4,
      no_of_users: 272,
      best_in: "Infrastructure",
    },
    ranking: 122,
  },
  {
    featured: false,
    college_logo:
      "https://logowik.com/content/uploads/images/iit-mandi-indian-institute-of-technology-mandi5013.jpg",
    college_name: "Indian Institute of Technology Mandi",
    college_city: "Mandi",
    college_state: "Himachal Pradesh",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 170,
    course_fees: "2,20,000",
    placement: {
      average_package: "22.50 LPA",
      highest_package: "45.00 LPA",
    },
    user_reviews: {
      rating: 8.6,
      no_of_users: 298,
      best_in: "Infrastructure",
    },
    ranking: 95,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "PSG College of Technology",
    college_city: "Coimbatore",
    college_state: "Tamil Nadu",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 130,
    course_fees: "3,00,000",
    placement: {
      average_package: "11.00 LPA",
      highest_package: "29.00 LPA",
    },
    user_reviews: {
      rating: 7.4,
      no_of_users: 450,
      best_in: "Social Life",
    },
    ranking: 90,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Birla Institute of Technology, Mesra",
    college_city: "Ranchi",
    college_state: "Jharkhand",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 140,
    course_fees: "3,20,000",
    placement: {
      average_package: "12.50 LPA",
      highest_package: "31.00 LPA",
    },
    user_reviews: {
      rating: 7.8,
      no_of_users: 480,
      best_in: "Infrastructure",
    },
    ranking: 95,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Delhi Technological University",
    college_city: "New Delhi",
    college_state: "Delhi NCR",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 135,
    course_fees: "3,50,000",
    placement: {
      average_package: "13.00 LPA",
      highest_package: "30.00 LPA",
    },
    user_reviews: {
      rating: 7.9,
      no_of_users: 490,
      best_in: "Social Life",
    },
    ranking: 100,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Indian Institute of Information Technology, Hyderabad",
    college_city: "Hyderabad",
    college_state: "Telangana",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 145,
    course_fees: "3,40,000",
    placement: {
      average_package: "14.50 LPA",
      highest_package: "32.00 LPA",
    },
    user_reviews: {
      rating: 8.0,
      no_of_users: 460,
      best_in: "Infrastructure",
    },
    ranking: 105,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Netaji Subhas University of Technology",
    college_city: "New Delhi",
    college_state: "Delhi NCR",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 140,
    course_fees: "3,30,000",
    placement: {
      average_package: "13.50 LPA",
      highest_package: "31.00 LPA",
    },
    user_reviews: {
      rating: 8.2,
      no_of_users: 470,
      best_in: "Social Life",
    },
    ranking: 110,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Birla Institute of Technology, Patna",
    college_city: "Patna",
    college_state: "Bihar",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 135,
    course_fees: "3,20,000",
    placement: {
      average_package: "12.00 LPA",
      highest_package: "30.00 LPA",
    },
    user_reviews: {
      rating: 7.6,
      no_of_users: 440,
      best_in: "Infrastructure",
    },
    ranking: 115,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name:
      "International Institute of Information Technology, Bangalore",
    college_city: "Bengaluru",
    college_state: "Karnataka",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 150,
    course_fees: "3,60,000",
    placement: {
      average_package: "15.00 LPA",
      highest_package: "33.00 LPA",
    },
    user_reviews: {
      rating: 8.4,
      no_of_users: 500,
      best_in: "Infrastructure",
    },
    ranking: 120,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "College of Engineering, Pune",
    college_city: "Pune",
    college_state: "Maharashtra",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 145,
    course_fees: "3,30,000",
    placement: {
      average_package: "13.50 LPA",
      highest_package: "31.00 LPA",
    },
    user_reviews: {
      rating: 8.1,
      no_of_users: 480,
      best_in: "Social Life",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Jamia Millia Islamia",
    college_city: "New Delhi",
    college_state: "Delhi NCR",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 150,
    course_fees: "3,20,000",
    placement: {
      average_package: "14.00 LPA",
      highest_package: "32.00 LPA",
    },
    user_reviews: {
      rating: 7.9,
      no_of_users: 490,
      best_in: "Social Life",
    },
    ranking: 130,
  },
  {
    featured: false,
    college_logo:
      "https://logowik.com/content/uploads/images/iit-gandhinagar-indian-institute-of-technology-gandhinagar5014.jpg",
    college_name: "Indian Institute of Technology Gandhinagar",
    college_city: "Gandhinagar",
    college_state: "Gujarat",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 150,
    course_fees: "2,10,000",
    placement: {
      average_package: "18.00 LPA",
      highest_package: "36.00 LPA",
    },
    user_reviews: {
      rating: 8.3,
      no_of_users: 255,
      best_in: "Social Life",
    },
    ranking: 128,
  },
  {
    featured: false,
    college_logo:
      "https://logowik.com/content/uploads/images/iit-jodhpur-indian-institute-of-technology-jodhpur5015.jpg",
    college_name: "Indian Institute of Technology Jodhpur",
    college_city: "Jodhpur",
    college_state: "Rajasthan",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 160,
    course_fees: "2,40,000",
    placement: {
      average_package: "20.00 LPA",
      highest_package: "40.00 LPA",
    },
    user_reviews: {
      rating: 8.5,
      no_of_users: 312,
      best_in: "Infrastructure",
    },
    ranking: 105,
  },
  {
    featured: false,
    college_logo:
      "https://logowik.com/content/uploads/images/iit-bhilai-indian-institute-of-technology-bhilai5016.jpg",
    college_name: "Indian Institute of Technology Bhilai",
    college_city: "Bhilai",
    college_state: "Chhattisgarh",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "2,20,000",
    placement: {
      average_package: "19.00 LPA",
      highest_package: "38.00 LPA",
    },
    user_reviews: {
      rating: 8.2,
      no_of_users: 290,
      best_in: "Social Life",
    },
    ranking: 112,
  },
  {
    featured: false,
    college_logo:
      "https://logowik.com/content/uploads/images/iit-goa-indian-institute-of-technology-goa5017.jpg",
    college_name: "Indian Institute of Technology Goa",
    college_city: "Goa",
    college_state: "Goa",
    institutions_approved: ["AICTE"],
    last_year_jee_advanced_btech_cse_cutoff: 145,
    course_fees: "2,30,000",
    placement: {
      average_package: "18.50 LPA",
      highest_package: "37.00 LPA",
    },
    user_reviews: {
      rating: 8.1,
      no_of_users: 278,
      best_in: "Infrastructure",
    },
    ranking: 118,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Sardar Vallabhbhai National Institute of Technology",
    college_city: "Surat",
    college_state: "Gujarat",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 135,
    course_fees: "3,20,000",
    placement: {
      average_package: "13.00 LPA",
      highest_package: "31.00 LPA",
    },
    user_reviews: {
      rating: 8.0,
      no_of_users: 460,
      best_in: "Infrastructure",
    },
    ranking: 115,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Birla Institute of Technology, Deoghar",
    college_city: "Deoghar",
    college_state: "Jharkhand",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 130,
    course_fees: "3,30,000",
    placement: {
      average_package: "12.50 LPA",
      highest_package: "30.00 LPA",
    },
    user_reviews: {
      rating: 7.8,
      no_of_users: 470,
      best_in: "Social Life",
    },
    ranking: 120,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Pandit Deendayal Petroleum University",
    college_city: "Gandhinagar",
    college_state: "Gujarat",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 140,
    course_fees: "3,40,000",
    placement: {
      average_package: "13.50 LPA",
      highest_package: "32.00 LPA",
    },
    user_reviews: {
      rating: 8.2,
      no_of_users: 480,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Indian Institute of Technology, Mandi",
    college_city: "Mandi",
    college_state: "Himachal Pradesh",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 145,
    course_fees: "3,50,000",
    placement: {
      average_package: "14.00 LPA",
      highest_package: "33.00 LPA",
    },
    user_reviews: {
      rating: 8.1,
      no_of_users: 490,
      best_in: "Social Life",
    },
    ranking: 130,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Indian Institute of Technology, Ropar",
    college_city: "Ropar",
    college_state: "Punjab",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 150,
    course_fees: "3,60,000",
    placement: {
      average_package: "15.00 LPA",
      highest_package: "34.00 LPA",
    },
    user_reviews: {
      rating: 8.3,
      no_of_users: 500,
      best_in: "Infrastructure",
    },
    ranking: 135,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Thapar Institute of Engineering & Technology",
    college_city: "Patiala",
    college_state: "Punjab",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "3,70,000",
    placement: {
      average_package: "15.50 LPA",
      highest_package: "35.00 LPA",
    },
    user_reviews: {
      rating: 8.4,
      no_of_users: 510,
      best_in: "Infrastructure",
    },
    ranking: 140,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Sardar Vallabhbhai National Institute of Technology",
    college_city: "Surat",
    college_state: "Gujarat",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 135,
    course_fees: "3,20,000",
    placement: {
      average_package: "13.00 LPA",
      highest_package: "31.00 LPA",
    },
    user_reviews: {
      rating: 8.0,
      no_of_users: 460,
      best_in: "Infrastructure",
    },
    ranking: 115,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Birla Institute of Technology, Deoghar",
    college_city: "Deoghar",
    college_state: "Jharkhand",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 130,
    course_fees: "3,30,000",
    placement: {
      average_package: "12.50 LPA",
      highest_package: "30.00 LPA",
    },
    user_reviews: {
      rating: 7.8,
      no_of_users: 470,
      best_in: "Social Life",
    },
    ranking: 120,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Pandit Deendayal Petroleum University",
    college_city: "Gandhinagar",
    college_state: "Gujarat",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 140,
    course_fees: "3,40,000",
    placement: {
      average_package: "13.50 LPA",
      highest_package: "32.00 LPA",
    },
    user_reviews: {
      rating: 8.2,
      no_of_users: 480,
      best_in: "Infrastructure",
    },
    ranking: 125,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Indian Institute of Technology, Mandi",
    college_city: "Mandi",
    college_state: "Himachal Pradesh",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 145,
    course_fees: "3,50,000",
    placement: {
      average_package: "14.00 LPA",
      highest_package: "33.00 LPA",
    },
    user_reviews: {
      rating: 8.1,
      no_of_users: 490,
      best_in: "Social Life",
    },
    ranking: 130,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Indian Institute of Technology, Ropar",
    college_city: "Ropar",
    college_state: "Punjab",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 150,
    course_fees: "3,60,000",
    placement: {
      average_package: "15.00 LPA",
      highest_package: "34.00 LPA",
    },
    user_reviews: {
      rating: 8.3,
      no_of_users: 500,
      best_in: "Infrastructure",
    },
    ranking: 135,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Thapar Institute of Engineering & Technology",
    college_city: "Patiala",
    college_state: "Punjab",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 155,
    course_fees: "3,70,000",
    placement: {
      average_package: "15.50 LPA",
      highest_package: "35.00 LPA",
    },
    user_reviews: {
      rating: 8.4,
      no_of_users: 510,
      best_in: "Infrastructure",
    },
    ranking: 140,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "National Institute of Technology, Calicut",
    college_city: "Calicut",
    college_state: "Kerala",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 130,
    course_fees: "3,40,000",
    placement: {
      average_package: "13.50 LPA",
      highest_package: "31.00 LPA",
    },
    user_reviews: {
      rating: 8.2,
      no_of_users: 490,
      best_in: "Social Life",
    },
    ranking: 145,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "Indian Institute of Technology, Bhilai",
    college_city: "Bhilai",
    college_state: "Chhattisgarh",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 135,
    course_fees: "3,50,000",
    placement: {
      average_package: "14.00 LPA",
      highest_package: "32.00 LPA",
    },
    user_reviews: {
      rating: 8.3,
      no_of_users: 500,
      best_in: "Infrastructure",
    },
    ranking: 150,
  },
  {
    featured: false,
    college_logo: "https://example.com/college_logo.jpg",
    college_name: "National Institute of Technology, Silchar",
    college_city: "Silchar",
    college_state: "Assam",
    institutions_approved: ["AICTE", "UGC"],
    last_year_jee_advanced_btech_cse_cutoff: 140,
    course_fees: "3,60,000",
    placement: {
      average_package: "14.50 LPA",
      highest_package: "33.00 LPA",
    },
    user_reviews: {
      rating: 8.4,
      no_of_users: 510,
      best_in: "Infrastructure",
    },
    ranking: 155,
  },
];
